// ─────────────────────────────────────────────────────────────────────────────
//  scripts/gen-job-schema.ts
//
//  Phase 5 §2.7: emits `schemas/job.schema.json` from `jobConfigSchema` via
//  `zod-to-json-schema`. Run via `pnpm gen:schema`; wired into `prebuild` so
//  the committed file is always up to date. Additive: never edit the
//  generated file by hand - regenerate.
// ─────────────────────────────────────────────────────────────────────────────

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import zodToJsonSchema from "zod-to-json-schema";

import { jobConfigSchema } from "../src/adapters/schemas/jobConfig.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const target = path.resolve(__dirname, "..", "schemas", "job.schema.json");

const json = zodToJsonSchema(jobConfigSchema, "JobConfig");
const header =
  "// Generated by `pnpm gen:schema` from src/adapters/schemas/jobConfig.ts.\n" +
  "// Do not edit by hand; regenerate via `pnpm gen:schema`.\n";

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, header + JSON.stringify(json, null, 2) + "\n", "utf8");
console.log(`Wrote ${path.relative(process.cwd(), target)}`);
